name: Cloud Formation Template Deployment in Azure
on:
  workflow_dispatch:
    inputs:
      msg: 
        description: 'Release version tag'
        default: 'v1.0.0'  
jobs:
  deploy-azure-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install beautifulsoup4
          python -m pip install paramiko
          python -m pip install art
          python -m pip install azure-cli==2.32.0
          az --version
          az config set extension.use_dynamic_install=yes_without_prompt 
      - name: Deploy Azure CFT
        run: |
          #python /home/runner/work/azure-waf-solution-template-/azure-waf-solution-template-/Tests/deploy.py ${{secrets.AZURE_SP}} ${{secrets.AZURE_PWD}}          
          python ${{secrets.RUNNER_PATH}}/Tests/deploy.py ${{secrets.AZURE_SP}} ${{secrets.AZURE_PWD}}
      - name: TEST Nginx App Protect WAF with Azure CFT
        run: |
          python ${{secrets.RUNNER_PATH}}/Tests/test.py ${{secrets.AZURE_SP}} ${{secrets.AZURE_PWD}}
      - name: Destroy Azure CFT
        run: |
          python ${{secrets.RUNNER_PATH}}/Tests/destroy.py ${{secrets.AZURE_SP}} ${{secrets.AZURE_PWD}}
      
